// Generated by scripts/build-idl.py - do not edit by hand.
//
// The address from `declare_id!`, split out so reading it does not
// pull the whole IDL into the bundle.
export const PROGRAM_ADDRESS = "A2WJAgqLpcZSkyqHu1cJA62gANDjiYx7M5Qyz9kZdoH3";
