// Generated by scripts/build-idl.py - do not edit by hand.
//
// The address from `declare_id!`, split out so reading it does not
// pull the whole IDL into the bundle.
export const PROGRAM_ADDRESS = "BuN69a1vsMdPQx6bWjaA7FJMbnBKo6yZ66cHrdyiTbiP";
