#!/usr/bin/env bash
#
# Run the integration suite against a local validator, without Anchor's IDL
# build step.
#
#   bash scripts/anchor-test.sh
#
# WHY THIS EXISTS
#
# `anchor test` runs `anchor build`, and `anchor build` runs an IDL generation
# step that compiles the program for the HOST with a `--features idl-build`
# flag. That step re-resolves dependencies and ignores this repo's Cargo.lock,
# so the careful pinning documented in BUILD.md does not protect it: it pulls
# whatever `proc-macro2` it likes and then fails to compile it against a modern
# host rustc, with errors about `proc_macro::SourceFile`.
#
# None of that is needed. The IDL is generated by `scripts/build-idl.py` and is
# committed under `idl/`, so this script builds the program with `--no-idl`,
# stages the committed IDL where `anchor.workspace` looks for it, and runs the
# tests with `--skip-build`.
#
# It also fixes the trap that `target/` being gitignored creates: a fresh clone
# has no program keypair, `anchor build` generates a random one, and every test
# then fails with `DeclaredProgramIdMismatch` because the deployed ID does not
# match `declare_id!`. Step 2 below reconciles them.

set -euo pipefail

cd "$(dirname "$0")/.."

bold=$'\033[1m'; green=$'\033[32m'; yellow=$'\033[33m'; red=$'\033[31m'; off=$'\033[0m'
step() { printf '\n%s%s%s\n' "$bold" "$1" "$off"; }
ok()   { printf '  %sok%s    %s\n' "$green" "$off" "$1"; }
warn() { printf '  %swarn%s  %s\n' "$yellow" "$off" "$1"; }
die()  { printf '\n  %serror%s %s\n\n' "$red" "$off" "$1" >&2; exit 1; }

# --- 0. preflight ----------------------------------------------------------

step "0/5  Checking the toolchain"

command -v anchor >/dev/null || die "anchor not found. Run scripts/setup-ubuntu.sh first."
command -v solana >/dev/null || die "solana not found. Run scripts/setup-ubuntu.sh first."
command -v node   >/dev/null || die "node not found. Install Node 18 or newer."
ok "anchor $(anchor --version 2>/dev/null | awk '{print $2}')"
ok "solana $(solana --version 2>/dev/null | awk '{print $2}')"

WALLET="${ANCHOR_WALLET:-$HOME/.config/solana/id.json}"
if [ ! -f "$WALLET" ]; then
  warn "no wallet at $WALLET; creating one (it is only used on a local validator)"
  solana-keygen new --no-bip39-passphrase --silent --outfile "$WALLET"
fi
ok "wallet $(solana-keygen pubkey "$WALLET")"

# --- 1. build the program, skipping the IDL step ---------------------------

step "1/5  Building the program (skipping Anchor's IDL step)"

anchor build --no-idl || die "anchor build --no-idl failed. That is a real program build failure, not the IDL issue."
ok "program built"

# --- 2. reconcile the program ID -------------------------------------------

step "2/5  Reconciling the program ID with the keypair on disk"

KEYPAIR="target/deploy/arclis-keypair.json"
[ -f "$KEYPAIR" ] || die "$KEYPAIR was not produced by the build."

DECLARED="$(grep -oP 'declare_id!\("\K[^"]+' programs/arclis/src/lib.rs)"
ON_DISK="$(node scripts/rotate-program-key.mjs --adopt 2>/dev/null | grep -oP 'on disk\s+\K\S+' || true)"

if [ -z "$ON_DISK" ]; then
  die "could not read the program ID from $KEYPAIR"
fi

if [ "$DECLARED" != "$ON_DISK" ]; then
  # `--adopt` above already rewrote declare_id!, Anchor.toml and idl/. The
  # program still has the old ID compiled into it, so it has to be rebuilt.
  warn "declare_id! was $DECLARED, keypair is $ON_DISK; rebuilding against the new ID"
  anchor build --no-idl || die "rebuild after the ID sync failed"
  ok "rebuilt against $ON_DISK"

  # Say this plainly, because it will bite on the next `git pull`. The keypair
  # lives in the gitignored `target/`, so every clone generates its own and the
  # program ID becomes a local fact. Three tracked files now differ from the
  # remote, and git will refuse to merge over them.
  cat <<NOTE

  ${yellow}Note:${off} this machine's program ID is now ${bold}${ON_DISK}${off}, which differs
  from the one in the repository. Three tracked files were rewritten to match:

      programs/arclis/src/lib.rs   Anchor.toml   idl/arclis.json

  That is expected. The keypair lives in the gitignored target/ directory, so
  every clone has its own ID, and these files are how the program learns it.

  It does mean \`git pull\` will refuse to merge over them. Before pulling:

      git stash push -m "local program id" programs/arclis/src/lib.rs Anchor.toml idl/arclis.json idl/arclis.ts
      git pull
      bash scripts/anchor-test.sh    # re-adopts your key; no need to unstash

NOTE
else
  ok "program ID $ON_DISK"
fi

# --- 3. stage the committed IDL --------------------------------------------

step "3/5  Staging the committed IDL"

[ -f idl/arclis.json ] || die "idl/arclis.json is missing. Run: python3 scripts/build-idl.py"

mkdir -p target/idl target/types
cp idl/arclis.json target/idl/arclis.json
cp idl/arclis.ts   target/types/arclis.ts

IDL_ID="$(node -e 'process.stdout.write(require("./target/idl/arclis.json").address)')"
[ "$IDL_ID" = "$ON_DISK" ] || die "the IDL says $IDL_ID but the keypair is $ON_DISK. Re-run: node scripts/rotate-program-key.mjs --adopt"

IX_COUNT="$(node -e 'process.stdout.write(String(require("./target/idl/arclis.json").instructions.length))')"
ok "target/idl/arclis.json ($IX_COUNT instructions, $IDL_ID)"

# --- 4. dependencies for the test runner -----------------------------------

step "4/5  Checking the test runner"

[ -d node_modules ] || { warn "node_modules missing; installing"; npm install --silent; }
command -v yarn >/dev/null || ok "yarn not installed (Anchor.toml uses npx, so that is fine)"
ok "ts-mocha available"

# --- 5. run ----------------------------------------------------------------

step "5/5  Running the integration suite"

printf '  a local validator starts automatically and is torn down after\n\n'
anchor test --skip-build
