#!/usr/bin/env bash
#
# Run the integration suite against a local validator, without Anchor's IDL
# build step.
#
#   bash scripts/anchor-test.sh
#
# WHY THIS EXISTS
#
# `anchor test` runs `anchor build`, and `anchor build` runs an IDL generation
# step that compiles the program for the HOST with a `--features idl-build`
# flag. That step re-resolves dependencies and ignores this repo's Cargo.lock,
# so the careful pinning documented in BUILD.md does not protect it: it pulls
# whatever `proc-macro2` it likes and then fails to compile it against a modern
# host rustc, with errors about `proc_macro::SourceFile`.
#
# None of that is needed. The IDL is generated by `scripts/build-idl.py` and is
# committed under `idl/`, so this script builds the program with `--no-idl`,
# stages the committed IDL where `anchor.workspace` looks for it, and runs the
# tests with `--skip-build`.
#
# It also fixes the trap that `target/` being gitignored creates: a fresh clone
# has no program keypair, `anchor build` generates a random one, and every test
# then fails with `DeclaredProgramIdMismatch` because the deployed ID does not
# match `declare_id!`. Step 2 below reconciles them.

set -euo pipefail

cd "$(dirname "$0")/.."

bold=$'\033[1m'; green=$'\033[32m'; yellow=$'\033[33m'; red=$'\033[31m'; off=$'\033[0m'
step() { printf '\n%s%s%s\n' "$bold" "$1" "$off"; }
ok()   { printf '  %sok%s    %s\n' "$green" "$off" "$1"; }
warn() { printf '  %swarn%s  %s\n' "$yellow" "$off" "$1"; }
die()  { printf '\n  %serror%s %s\n\n' "$red" "$off" "$1" >&2; exit 1; }

# --- 0. preflight ----------------------------------------------------------

step "0/6  Checking the toolchain"

command -v anchor >/dev/null || die "anchor not found. Run scripts/setup-ubuntu.sh first."
command -v solana >/dev/null || die "solana not found. Run scripts/setup-ubuntu.sh first."
command -v node   >/dev/null || die "node not found. Install Node 18 or newer."
ok "anchor $(anchor --version 2>/dev/null | awk '{print $2}')"
ok "solana $(solana --version 2>/dev/null | awk '{print $2}')"

WALLET="${ANCHOR_WALLET:-$HOME/.config/solana/id.json}"
if [ ! -f "$WALLET" ]; then
  warn "no wallet at $WALLET; creating one (it is only used on a local validator)"
  solana-keygen new --no-bip39-passphrase --silent --outfile "$WALLET"
fi
ok "wallet $(solana-keygen pubkey "$WALLET")"

# --- 1. build the program, skipping the IDL step ---------------------------

step "1/6  Building the program (skipping Anchor's IDL step)"

anchor build --no-idl || die "anchor build --no-idl failed. That is a real program build failure, not the IDL issue."
ok "program built"

# --- 2. reconcile the program ID -------------------------------------------

step "2/6  Reconciling the program ID with the keypair on disk"

KEYPAIR="target/deploy/arclis-keypair.json"
[ -f "$KEYPAIR" ] || die "$KEYPAIR was not produced by the build."

DECLARED="$(grep -oP 'declare_id!\("\K[^"]+' programs/arclis/src/lib.rs)"
ON_DISK="$(node scripts/rotate-program-key.mjs --adopt 2>/dev/null | grep -oP 'on disk\s+\K\S+' || true)"

if [ -z "$ON_DISK" ]; then
  die "could not read the program ID from $KEYPAIR"
fi

if [ "$DECLARED" != "$ON_DISK" ]; then
  # `--adopt` above already rewrote declare_id!, Anchor.toml and idl/. The
  # program still has the old ID compiled into it, so it has to be rebuilt.
  warn "declare_id! was $DECLARED, keypair is $ON_DISK; rebuilding against the new ID"
  anchor build --no-idl || die "rebuild after the ID sync failed"
  ok "rebuilt against $ON_DISK"

  # Say this plainly, because it will bite on the next `git pull`. The keypair
  # lives in the gitignored `target/`, so every clone generates its own and the
  # program ID becomes a local fact. Three tracked files now differ from the
  # remote, and git will refuse to merge over them.
  cat <<NOTE

  ${yellow}Note:${off} this machine's program ID is now ${bold}${ON_DISK}${off}, which differs
  from the one in the repository. Three tracked files were rewritten to match:

      programs/arclis/src/lib.rs   Anchor.toml   idl/arclis.json

  That is expected. The keypair lives in the gitignored target/ directory, so
  every clone has its own ID, and these files are how the program learns it.

  It does mean \`git pull\` will refuse to merge over them. Before pulling:

      git stash push -m "local program id" programs/arclis/src/lib.rs Anchor.toml idl/arclis.json idl/arclis.ts
      git pull
      bash scripts/anchor-test.sh    # re-adopts your key; no need to unstash

NOTE
else
  ok "program ID $ON_DISK"
fi

# --- 3. stage the committed IDL --------------------------------------------

step "3/6  Staging the committed IDL"

[ -f idl/arclis.json ] || die "idl/arclis.json is missing. Run: python3 scripts/build-idl.py"

mkdir -p target/idl target/types
cp idl/arclis.json target/idl/arclis.json
cp idl/arclis.ts   target/types/arclis.ts

IDL_ID="$(node -e 'process.stdout.write(require("./target/idl/arclis.json").address)')"
[ "$IDL_ID" = "$ON_DISK" ] || die "the IDL says $IDL_ID but the keypair is $ON_DISK. Re-run: node scripts/rotate-program-key.mjs --adopt"

IX_COUNT="$(node -e 'process.stdout.write(String(require("./target/idl/arclis.json").instructions.length))')"
ok "target/idl/arclis.json ($IX_COUNT instructions, $IDL_ID)"

# --- 4. dependencies for the test runner -----------------------------------

step "4/6  Checking the test runner"

[ -d node_modules ] || { warn "node_modules missing; installing"; npm install --silent; }
command -v yarn >/dev/null || ok "yarn not installed (Anchor.toml uses npx, so that is fine)"
ok "ts-mocha available"

# --- 5. clear the way for the validator ------------------------------------

step "5/6  Preparing the local validator"

# A stray validator from an aborted run holds the ports and the new one dies
# silently. This is the single most common reason for "does not look started".
# `-x` matches the executable name, never the command line. `pgrep -f` would
# also match any shell whose command line happens to contain the string, and
# the matching `pkill -f` would then kill the terminal you are running this in.
if pgrep -x solana-test-validator >/dev/null 2>&1; then
  warn "a solana-test-validator is already running; stopping it"
  pkill -x solana-test-validator || true
  sleep 3
else
  ok "no stray validator"
fi

# A half-written ledger from a killed run wedges startup. It is disposable:
# `anchor test` builds a fresh one every time.
if [ -d .anchor/test-ledger ] || [ -d test-ledger ]; then
  rm -rf .anchor/test-ledger test-ledger
  ok "cleared the stale ledger"
fi

# The classic WSL killer. Ubuntu ships a 1024 descriptor limit; the validator
# opens far more than that and exits during genesis with nothing useful on
# stdout. Raising it for this shell is enough, and needs no privileges as long
# as the hard limit allows it.
ulimit -n 65536 2>/dev/null || ulimit -n "$(ulimit -Hn)" 2>/dev/null || true
NOFILE="$(ulimit -n)"
if [ "$NOFILE" != "unlimited" ] && [ "$NOFILE" -lt 10000 ]; then
  warn "open-file limit is only $NOFILE; the validator usually needs ~65536"
  printf '        to raise the hard limit permanently, add to /etc/security/limits.conf:\n'
  printf '            %s hard nofile 65536\n' "$(whoami)"
  printf '        then close and reopen the WSL terminal.\n'
else
  ok "open files $NOFILE"
fi

# The validator wants roughly 1.5GB. WSL2 defaults to half the host's RAM, so
# an older machine can land under that without saying so.
if [ -r /proc/meminfo ]; then
  AVAIL_MB=$(( $(awk '/MemAvailable/ {print $2}' /proc/meminfo) / 1024 ))
  if [ "$AVAIL_MB" -lt 1500 ]; then
    warn "only ${AVAIL_MB}MB of memory available; the validator wants ~1500MB"
    printf '        in Windows, create %%UserProfile%%\\.wslconfig with:\n'
    printf '            [wsl2]\n            memory=4GB\n'
    printf '        then run `wsl --shutdown` in PowerShell and reopen Ubuntu.\n'
  else
    ok "memory ${AVAIL_MB}MB available"
  fi
fi

# --- 6. run ----------------------------------------------------------------

step "6/6  Running the integration suite"

LOG=".anchor/test-ledger/test-ledger-log.txt"

if [ "${USE_RUNNING_VALIDATOR:-}" = "1" ]; then
  printf '  using a validator you started yourself\n\n'
  anchor test --skip-build --skip-local-validator
  exit $?
fi

printf '  starting a local validator (up to 90s on a slower machine)\n\n'

set +e
anchor test --skip-build
RC=$?
set -e

if [ "$RC" -ne 0 ]; then
  # Anchor points at the log and leaves you to find it. Print it here: it is
  # the only thing that says why the validator did not come up.
  if [ -f "$LOG" ]; then
    step "Validator log (last 40 lines of $LOG)"
    tail -40 "$LOG"
  else
    step "No validator log was written"
    printf '  %s does not exist, so the validator died before it could open it.\n' "$LOG"
    printf '  That is almost always the descriptor limit or memory, both reported above.\n'
  fi

  cat <<'NEXT'

  If the validator is the problem rather than the tests, run it yourself in a
  second terminal, where its output is visible:

      solana-test-validator --reset

  then, in this one:

      USE_RUNNING_VALIDATOR=1 bash scripts/anchor-test.sh

NEXT
fi

exit "$RC"
