#!/usr/bin/env python3
"""Self-host the fallback UI font.

Arclis is designed for **After** (display) and **Newblack** (text). Both are
commercial, so they are not in this repository. `tokens.css` lists them first
and falls back to Plus Jakarta Sans, which is close in construction - geometric,
wide apertures, tall x-height - and open licensed.

Self-hosting rather than linking Google Fonts means the interface renders
identically offline, in CI, and behind a proxy, with no third-party request on
first paint.

    python3 scripts/fetch-fonts.py

It also self-hosts JetBrains Mono, which the interface uses for tickers,
addresses, basis points and anything else a reader compares row against row.

Writes woff2 files plus `fonts.css` into app/public/fonts/.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

# Two families, each self-hosted. The sans is the UI fallback; the mono is
# used for tickers, addresses, basis points and anything else where a reader is
# comparing one row against another and needs the digits to line up.
FAMILIES = [
    ("Plus Jakarta Sans", "Plus+Jakarta+Sans:wght@400;500;600;700;800", "pjs"),
    ("JetBrains Mono", "JetBrains+Mono:wght@400;500;600;700", "jbm"),
]
# Latin only. The other subsets are dead weight for this interface.
KEEP_SUBSETS = {"latin", "latin-ext"}
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120 Safari/537.36"

OUT = Path(__file__).resolve().parent.parent / "app" / "public" / "fonts"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def parse_faces(query: str):
    """Pull (subset, weight, url, unicode-range) out of one family's CSS."""
    css = fetch(
        f"https://fonts.googleapis.com/css2?family={query}&display=swap"
    ).decode("utf-8")

    # Each @font-face block is preceded by a `/* subset */` comment. Split on
    # those so a block is never matched against another block's URL - which is
    # exactly what a line-offset grep gets wrong.
    blocks = re.split(r"/\*\s*([\w-]+)\s*\*/", css)[1:]
    faces = []
    for subset, body in zip(blocks[0::2], blocks[1::2]):
        if subset not in KEEP_SUBSETS:
            continue
        weight = re.search(r"font-weight:\s*(\d+)", body)
        url = re.search(r"src:\s*url\(([^)]+)\)", body)
        rng = re.search(r"unicode-range:\s*([^;]+);", body)
        if not (weight and url):
            continue
        faces.append((subset, weight.group(1), url.group(1), rng.group(1) if rng else None))
    return faces


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* Generated by scripts/fetch-fonts.py - do not edit by hand. */",
        "/*",
        " * Fallback for After (display) and Newblack (text), which are commercial",
        " * and not redistributed here. Drop the licensed files beside this one as",
        " * after.woff2 / newblack.woff2 and uncomment the two blocks below; the",
        " * stack in tokens.css already prefers them.",
        " */",
        "",
        "/*",
        "@font-face { font-family: 'After'; src: url('/fonts/after.woff2') format('woff2');",
        "  font-weight: 400 800; font-display: swap; }",
        "@font-face { font-family: 'Newblack'; src: url('/fonts/newblack.woff2') format('woff2');",
        "  font-weight: 300 700; font-display: swap; }",
        "*/",
        "",
    ]

    total = 0
    for family, query, prefix in FAMILIES:
        faces = parse_faces(query)
        if not faces:
            raise SystemExit(
                f"no font faces parsed for {family} - the Google Fonts CSS format may have changed"
            )
        print(f"\n  {family}")
        for subset, weight, url, rng in sorted(faces, key=lambda f: (f[1], f[0])):
            name = f"{prefix}-{subset}-{weight}.woff2"
            (OUT / name).write_bytes(fetch(url))
            size = (OUT / name).stat().st_size
            print(f"    {name:<28} {size / 1024:5.1f} KB")
            lines += [
                "@font-face {",
                f"  font-family: '{family}';",
                "  font-style: normal;",
                f"  font-weight: {weight};",
                "  font-display: swap;",
                f"  src: url('/fonts/{name}') format('woff2');",
                *( [f"  unicode-range: {rng};"] if rng else [] ),
                "}",
                "",
            ]
        total += len(faces)

    (OUT / "fonts.css").write_text("\n".join(lines))
    print(f"\n  fonts.css written with {total} faces")


if __name__ == "__main__":
    main()
